flowchart DA_1
    A[Accueil] --> B[Se connecter]
    B[Se connecter] --> C{Is it?}
    C -- connexion réussie --> D[Demmarrer une Conversation]
    C -- compte inexistant-->  X[Creer un Compte]
    X -- Creation avec succès, retour à Acceuil --> A
    D --> Z[Paramètre par défaut de la conversation]
    Z --> E{Modifier?}
    E -- Oui --> F[Modifier les parametres]
    E -- Non, continuer--> G[Discussion]
    F --> G
    G --> H[End]