graph global
  A["Accueil"] --> B["Se connecter"]
  A --> C["Créer un compte"]
  A --> D["Quitter"]

  B --> E["Utilisateur"]

  %% Sous-espace utilisateur
  subgraph "Espace Utilisateur"
    direction TB
    F["Démarrer une conversation"]
    G["Historique de conversation"]
    H["Voir les statistiques"]
    I["Se déconnecter"]
    J["Supprimer mon compte"]
  end

  E --> F
  E --> G
  E --> H
  E --> I
  E --> J

  %% Historique
  subgraph "Options Historique"
    direction TB
    G1["Voir l’historique"]
    G2["Rechercher une conversation"]
    G21["Par mot-clé ou date"]
  end

  G --> G1
  G --> G2
  G2 --> G21
  G1 --> Disc["Discussion"]
  G21 --> Disc

  %% Nouvelle conversation
  subgraph "Nouvelle Conversation"
    direction TB
    F1["Paramètres de discussion"]
  end

  F --> F1
  F1 --> Disc

  %% Fin
  Disc --> K["Fin"]
