flowchart TD
    A[Accueil] --> B[Se connecter]
    B[Se connecter] --> C{Is it?}
    C -- connexion réussie --> D[Historique de Conversation]
    C -- compte inexistant-->  X[Creer un Compte]
    X -- Creation avec succès, retour à Acceuil --> A
    
    D --> Z[Rechercher une conversation]
    Z --> E{par Date?}
    E -- Oui --> F[Recherche par Date]
    E -- Non, par mots clés--> G[Recherche par mots clés]
    G --> Y[Discussion]
    F --> Y
    Y --> H[End]